Add functionality to the wrapper script to clean up stale build links created by spack install.

diff --git a/activate_h3env b/activate_h3env
--- a/activate_h3env
+++ b/activate_h3env
@@ -27,25 +27,23 @@ _create-link() {
     fi
 }
 
+# Perform cleanup tasks
+cleanup_h3env() {
+  # Just update build links for now
+  updatelinks_h3env
+}
+
 # Remove convenience aliases/function definitions and deactivate the env
 deactivate_h3env() {
     unset -f _create-link
+    unset -f cleanup_h3env
     unset -f deactivate_h3env
-    unset -f _get_installed_h3_hashes
     unalias help_h3env
     unset -f in_h3env
     unset REPO_ROOT
-    unset -f update_build_links
+    unset -f updatelinks_h3env
     unset -f usage_h3env
     spack env deactivate
-}
-
-# Use 'spack find' to get the hashes of currently installed hermes-3 packages
-# Discard stderr to suppress errror message when no installs are found
-_get_installed_h3_hashes() {
-    local identifier_fmt="{hash:7}"
-    spack find --format "$identifier_fmt" "hermes-3" 2> /dev/null
-    return $?
 }
 
 # Run commands in the build environment
@@ -62,16 +60,21 @@ in_h3env() {
 
 # Update the links at <REPO_ROOT>/builds/spack-* such that there's
 # exactly one link for every package returned by 'spack find hermes-3'
-update_build_links() {
+updatelinks_h3env() {
   local link_prefix="builds/spack-"
+  
+  # Use 'spack find' to get the hashes of currently installed hermes-3 packages
+  # Discard stderr to suppress error message when no installs are found
+  local identifier_fmt="{hash:7}"
+  installed_hashes=$(spack find --format "$identifier_fmt" "hermes-3" 2> /dev/null)
+
   # Create any links for installed packages that don't exist already
-  for hash in $(_get_installed_h3_hashes); do
+  for hash in $installed_hashes; do
     spack_build_dir=$(spack location -b "hermes-3/$hash")
     _create-link "${spack_build_dir}" "${link_prefix}${hash}"
   done
 
-  # Check whether existing links are still valid
-  # Could also just use find -xtype l ?
+  # Check whether existing links are still valid (Could also just use find -xtype l ?)
   for l in ${REPO_ROOT}/${link_prefix}*; do
     # Skip if l isn't a link (also guards against case where pattern has zero matches)
     [ ! -L "$l" ] && break;
@@ -83,15 +86,27 @@ update_build_links() {
       rm -f $l
     fi
   done
+
+  # Also clean up top-level build links created by spack install
+  spack_link_paths=$(find "$REPO_ROOT" -type l -regextype posix-egrep -regex "${REPO_ROOT}/build-.*-[a-z0-9]{7}$")
+  for link_path in $spack_link_paths; do
+      local hash="${link_path:(-7)}"
+      if ! [[ " ${installed_hashes[*]} " =~ " ${hash} " ]]
+      then
+          echo "    Removing stale spack link at ${link_path}"
+          rm -Rf "$link_path" > /dev/null
+      fi
+  done
 }
 
 # Print help/usage info
 usage_h3env() {
-    echo " Activate the environment                             :  . activate_h3env"
-    echo " Deactivate the environment                           :  deactivate_h3env"
-    echo " Run a command in the build environment               :  in_h3env [args]"
-    echo '                                                           e.g. export h3_build="./builds/my_build" && in_h3env cmake -B "$h3_build" && in_h3env cmake --build "$h3_build" -j8'
-    echo " Update links to installed builds in ./builds/spack-* : update_build_links"
+    echo " . activate_h3env  : Activate the environment"
+    echo " cleanup_h3env     : Perform cleanup tasks (includes updatelinks_h3env)"
+    echo " deactivate_h3env  : Deactivate the environment"
+    echo " help_h3env        : Show this message"
+    echo ' in_h3env [args]   : Run a command in the build environment: (e.g. export h3_build="./builds/my_build" && in_h3env cmake -B "$h3_build" && in_h3env cmake --build "$h3_build" -j8)'
+    echo " updatelinks_h3env : Update all build links (Remove stale links and add new ones in ./builds/spack-* where necessary)"
 }
 alias help_h3env=usage_h3env
 
@@ -119,4 +134,4 @@ fi
 spacktivate . -p
 
 # Update build links
-update_build_links
+cleanup_h3env
